apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa-gatekeeper
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-58"
  labels:
    app.kubernetes.io/name: opa-gatekeeper
    app.kubernetes.io/part-of: sovereign-security
spec:
  revisionHistoryLimit: 3
  project: default
  source:
    repoURL: https://github.com/libliflin/sovereign
    targetRevision: HEAD
    path: charts/opa-gatekeeper
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
