apiVersion: v2
name: reportportal
description: ReportPortal test result history — Keycloak OIDC, PostgreSQL, Elasticsearch, RabbitMQ
type: application
version: 0.1.0
appVersion: "24.1"

dependencies:
  - name: postgresql
    version: "13.4.4"
    repository: "https://charts.bitnami.com/bitnami"
    alias: postgresql
    condition: postgresql.enabled
  - name: rabbitmq
    version: "12.6.1"
    repository: "https://charts.bitnami.com/bitnami"
    alias: rabbitmq
    condition: rabbitmq.enabled
  - name: elasticsearch
    version: "19.13.9"
    repository: "https://charts.bitnami.com/bitnami"
    alias: elasticsearch
    condition: elasticsearch.enabled
