#!/usr/bin/env bash
# bootstrap/frontdoor/cloudflare.sh — Cloudflare Tunnel + Zero Trust front door
#
# This provider closes ALL inbound ports on your VPS and routes traffic through
# a Cloudflare Tunnel (free tier). The tunnel is outbound-only from the VPS:
# no ports need to be open in UFW or your cloud provider's firewall.
#
# Security posture:
#   - VPS has zero inbound ports open (no SSH, no 80, no 443, no 6443)
#   - All traffic flows through Cloudflare's edge → tunnel → cluster
#   - SSH access requires Cloudflare Zero Trust Access (browser SSH or WARP)
#   - DDoS protection and WAF are included at the Cloudflare edge layer
#
# Requirements (set in bootstrap/config.yaml):
#   cloudflare.apiToken   — API token: Tunnel:Edit + DNS:Edit permissions
#   cloudflare.accountId  — Account ID (Cloudflare dashboard → right sidebar)
#   cloudflare.tunnelName — Tunnel name (e.g. "sovereign-prod")
#   cloudflare.zoneId     — Zone ID for your domain (dashboard → right sidebar)
#
# After bootstrap, manage access via: https://one.dash.cloudflare.com
# ─────────────────────────────────────────────────────────────────────────────
# shellcheck source=bootstrap/frontdoor/interface.sh
# shellcheck source=bootstrap/providers/cloudflare-dns.sh

# State files (written by frontdoor_provision, read by later hooks)
_CF_STATE_TUNNEL_ID="/tmp/sovereign-frontdoor-tunnel-id"
_CF_STATE_TUNNEL_CREDS="/tmp/sovereign-frontdoor-tunnel-creds.json"
_CF_STATE_CLOUDFLARED_CONFIG="/tmp/sovereign-frontdoor-cloudflared.yml"

# _cf_load_config
# ─────────────────────────────────────────────────────────────────────────────
# Read Cloudflare configuration from SOVEREIGN_CONFIG (config.yaml) and export
# environment variables consumed by cloudflare-dns.sh helpers.
_cf_load_config() {
  if [[ -z "${SOVEREIGN_CONFIG:-}" ]]; then
    echo "ERROR: SOVEREIGN_CONFIG is not set. Call from bootstrap.sh." >&2
    return 1
  fi

  if ! command -v yq &>/dev/null; then
    echo "ERROR: 'yq' is required but not found in PATH." >&2
    return 1
  fi

  CF_API_TOKEN="$(yq '.cloudflare.apiToken' "${SOVEREIGN_CONFIG}")"
  CF_ACCOUNT_ID="$(yq '.cloudflare.accountId' "${SOVEREIGN_CONFIG}")"
  CF_TUNNEL_NAME="$(yq '.cloudflare.tunnelName // "sovereign"' "${SOVEREIGN_CONFIG}")"
  CF_ZONE_ID="$(yq '.cloudflare.zoneId' "${SOVEREIGN_CONFIG}")"

  if [[ -z "$CF_API_TOKEN" || "$CF_API_TOKEN" == "null" ]]; then
    echo "ERROR: cloudflare.apiToken is required in config.yaml" >&2
    return 1
  fi
  if [[ -z "$CF_ACCOUNT_ID" || "$CF_ACCOUNT_ID" == "null" ]]; then
    echo "ERROR: cloudflare.accountId is required in config.yaml" >&2
    return 1
  fi
  if [[ -z "$CF_ZONE_ID" || "$CF_ZONE_ID" == "null" ]]; then
    echo "ERROR: cloudflare.zoneId is required in config.yaml" >&2
    return 1
  fi

  export CF_API_TOKEN CF_ACCOUNT_ID CF_TUNNEL_NAME CF_ZONE_ID

  # Source the shared API helpers
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  # shellcheck disable=SC1091
  source "${script_dir}/../providers/cloudflare-dns.sh"
}

# frontdoor_provision
# ─────────────────────────────────────────────────────────────────────────────
# Create a Cloudflare Tunnel via API and write credentials to state files.
# Runs locally before any nodes are provisioned.
frontdoor_provision() {
  echo "==> [frontdoor/cloudflare] Provisioning Cloudflare Tunnel..."
  _cf_load_config

  # Generate a 32-byte random tunnel secret
  local tunnel_secret
  tunnel_secret="$(openssl rand -base64 32 | tr -d '\n')"

  echo "  Creating tunnel: ${CF_TUNNEL_NAME}"
  local response
  response="$(cf_tunnel_create "${CF_TUNNEL_NAME}" "${tunnel_secret}")"

  # Extract tunnel ID from response
  local tunnel_id
  tunnel_id="$(printf '%s' "$response" | \
    python3 -c "import sys,json; d=json.load(sys.stdin); print(d['result']['id'])")"

  if [[ -z "$tunnel_id" ]]; then
    echo "ERROR: Failed to extract tunnel ID from API response." >&2
    printf '%s\n' "$response" >&2
    return 1
  fi

  echo "  Tunnel created: ${tunnel_id}"

  # Extract credentials JSON from response
  local creds_json
  creds_json="$(printf '%s' "$response" | \
    python3 -c "import sys,json; d=json.load(sys.stdin); print(json.dumps(d['result']['credentials_file'], indent=2))")"

  # Write state files for later hooks
  printf '%s' "$tunnel_id" > "${_CF_STATE_TUNNEL_ID}"
  printf '%s\n' "$creds_json" > "${_CF_STATE_TUNNEL_CREDS}"

  # Write cloudflared config.yml (applied to each node by frontdoor_install_agent)
  cat > "${_CF_STATE_CLOUDFLARED_CONFIG}" <<EOF
# cloudflared config — generated by sovereign bootstrap
tunnel: ${tunnel_id}
credentials-file: /etc/cloudflared/credentials.json

# Route all ingress traffic to the K3s ingress controller on localhost.
# Cloudflare handles TLS termination and routing at the edge.
ingress:
  - service: http://localhost:80
EOF

  echo "  State written to /tmp/sovereign-frontdoor-*"
  echo "==> [frontdoor/cloudflare] Tunnel provisioned: ${CF_TUNNEL_NAME} (${tunnel_id})"
}

# frontdoor_install_agent [NODE_IP...]
# ─────────────────────────────────────────────────────────────────────────────
# Deploy cloudflared on every node using TWO mechanisms for HA:
#
#   1. K3s DaemonSet manifest (primary, GitOps-friendly):
#      Writes a cloudflared DaemonSet to /var/lib/rancher/k3s/server/manifests/
#      on the first node. K3s auto-deploys it cluster-wide. The DaemonSet
#      ensures cloudflared runs on EVERY node automatically — new nodes added
#      to the cluster get cloudflared without manual intervention.
#
#   2. systemd service (fallback, pre-cluster):
#      Also installs cloudflared as a systemd unit on each node directly.
#      This ensures the tunnel is active even before K3s starts the DaemonSet.
#
# Together these ensure: if a node reboots before K3s is ready, systemd starts
# the tunnel. Once K3s is running, the DaemonSet takes over management.
frontdoor_install_agent() {
  echo "==> [frontdoor/cloudflare] Installing cloudflared on nodes (systemd + DaemonSet)..."

  if [[ ! -f "${_CF_STATE_TUNNEL_ID}" ]]; then
    echo "ERROR: Tunnel state not found. Run frontdoor_provision first." >&2
    return 1
  fi

  local tunnel_id
  tunnel_id="$(cat "${_CF_STATE_TUNNEL_ID}")"

  local creds_json
  creds_json="$(cat "${_CF_STATE_TUNNEL_CREDS}")"

  local cloudflared_config
  cloudflared_config="$(cat "${_CF_STATE_CLOUDFLARED_CONFIG}")"

  local ssh_key="${SOVEREIGN_SSH_KEY:-}"
  if [[ -z "$ssh_key" ]]; then
    echo "ERROR: SOVEREIGN_SSH_KEY is not set." >&2
    return 1
  fi

  local SSH_OPTS=(-o StrictHostKeyChecking=no -o ConnectTimeout=30 -i "$ssh_key")

  # ── Write the cloudflared DaemonSet manifest to node-1 ──────────────────────
  # K3s picks up manifests from /var/lib/rancher/k3s/server/manifests/ and
  # deploys them cluster-wide. The DaemonSet ensures cloudflared runs on all
  # nodes — including any nodes added to the cluster after bootstrap.
  local first_node="$1"
  echo "  --> Writing cloudflared DaemonSet manifest to node-1 (${first_node})..."

  # The credentials and config must be in a Secret/ConfigMap for the DaemonSet.
  # We write them as a K3s manifest alongside the DaemonSet.
  cat > /tmp/sovereign-cloudflared-daemonset.yaml <<DAEMONSET_EOF
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
type: Opaque
stringData:
  credentials.json: |
$(printf '%s' "$creds_json" | sed 's/^/    /')
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yml: |
    tunnel: ${tunnel_id}
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - service: http://localhost:80
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudflared
  namespace: cloudflared
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config.yml
        - run
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-credentials
              key: credentials.json
              optional: true
        volumeMounts:
        - name: credentials
          mountPath: /etc/cloudflared/credentials.json
          subPath: credentials.json
          readOnly: true
        - name: config
          mountPath: /etc/cloudflared/config.yml
          subPath: config.yml
          readOnly: true
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 2000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: credentials
        secret:
          secretName: cloudflared-credentials
      - name: config
        configMap:
          name: cloudflared-config
DAEMONSET_EOF

  ssh "${SSH_OPTS[@]}" "root@${first_node}" \
    'mkdir -p /var/lib/rancher/k3s/server/manifests'
  cat /tmp/sovereign-cloudflared-daemonset.yaml | \
    ssh "${SSH_OPTS[@]}" "root@${first_node}" \
    'cat > /var/lib/rancher/k3s/server/manifests/cloudflared-daemonset.yaml'
  echo "  --> DaemonSet manifest written. K3s will deploy it cluster-wide."

  # ── Also install cloudflared via systemd on each node (pre-cluster fallback) ─
  for node_ip in "$@"; do
    echo "  --> Installing cloudflared systemd service on ${node_ip}..."

    # Install cloudflared from the official Cloudflare APT repository
    ssh "${SSH_OPTS[@]}" "root@${node_ip}" \
      'curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg \
         -o /usr/share/keyrings/cloudflare-main.gpg && \
       echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" \
         > /etc/apt/sources.list.d/cloudflared.list && \
       apt-get update -qq && \
       DEBIAN_FRONTEND=noninteractive apt-get install -y -qq cloudflared'

    # Create cloudflared config directory
    ssh "${SSH_OPTS[@]}" "root@${node_ip}" 'mkdir -p /etc/cloudflared'

    # Push tunnel credentials JSON
    printf '%s\n' "$creds_json" | \
      ssh "${SSH_OPTS[@]}" "root@${node_ip}" \
        'cat > /etc/cloudflared/credentials.json && chmod 600 /etc/cloudflared/credentials.json'

    # Push cloudflared config.yml
    printf '%s\n' "$cloudflared_config" | \
      ssh "${SSH_OPTS[@]}" "root@${node_ip}" \
        'cat > /etc/cloudflared/config.yml'

    # Install and start cloudflared as a systemd service
    ssh "${SSH_OPTS[@]}" "root@${node_ip}" \
      'cloudflared service install && \
       systemctl daemon-reload && \
       systemctl enable cloudflared && \
       systemctl restart cloudflared && \
       sleep 2 && \
       systemctl is-active cloudflared || (journalctl -u cloudflared -n 20 >&2; exit 1)'

    echo "  --> cloudflared systemd service running on ${node_ip} (tunnel: ${tunnel_id})"
  done

  echo "==> [frontdoor/cloudflare] cloudflared deployed:"
  echo "    - DaemonSet manifest written to K3s manifests dir (cluster-wide)"
  echo "    - systemd service installed on all ${#} node(s) (pre-cluster fallback)"
}

# frontdoor_configure_dns
# ─────────────────────────────────────────────────────────────────────────────
# Create a wildcard CNAME record routing *.<domain> to the Cloudflare Tunnel.
# The CNAME target is <tunnel-id>.cfargotunnel.com (Cloudflare's tunnel endpoint).
frontdoor_configure_dns() {
  echo "==> [frontdoor/cloudflare] Configuring DNS..."

  if [[ ! -f "${_CF_STATE_TUNNEL_ID}" ]]; then
    echo "ERROR: Tunnel state not found. Run frontdoor_provision first." >&2
    return 1
  fi

  local tunnel_id
  tunnel_id="$(cat "${_CF_STATE_TUNNEL_ID}")"

  _cf_load_config

  local domain="${SOVEREIGN_DOMAIN:-}"
  if [[ -z "$domain" ]]; then
    echo "ERROR: SOVEREIGN_DOMAIN is not set." >&2
    return 1
  fi

  local tunnel_hostname="${tunnel_id}.cfargotunnel.com"

  echo "  Creating wildcard CNAME: *.${domain} → ${tunnel_hostname}"
  cf_dns_upsert "*.${domain}" CNAME "${tunnel_hostname}" "true"

  # Also create the root domain CNAME so the apex resolves via the tunnel
  echo "  Creating apex CNAME: ${domain} → ${tunnel_hostname}"
  cf_dns_upsert "${domain}" CNAME "${tunnel_hostname}" "true"

  echo "==> [frontdoor/cloudflare] DNS configured. Propagation may take 1-2 minutes."
}

# frontdoor_allowed_cidrs
# ─────────────────────────────────────────────────────────────────────────────
# Print Cloudflare's published IP ranges (v4 + v6). These are the only IPs
# that will ever connect to the VPS when using a Cloudflare Tunnel.
#
# NOTE: With a Cloudflare Tunnel the VPS needs NO inbound ports open at all —
# the tunnel connection is outbound from the VPS. These CIDRs are provided so
# UFW can be configured with an allow-rule as a defence-in-depth measure, but
# even without it the tunnel works because cloudflared initiates the connection.
frontdoor_allowed_cidrs() {
  # Fetch Cloudflare's published IP ranges
  # These lists are maintained by Cloudflare at these stable URLs
  curl -s --max-time 10 https://www.cloudflare.com/ips-v4 || true
  echo ""
  curl -s --max-time 10 https://www.cloudflare.com/ips-v6 || true
}

# frontdoor_connection_info
# ─────────────────────────────────────────────────────────────────────────────
# Print instructions for connecting to the cluster after bootstrap completes.
frontdoor_connection_info() {
  local domain="${SOVEREIGN_DOMAIN:-your-domain.com}"
  local tunnel_id=""
  if [[ -f "${_CF_STATE_TUNNEL_ID}" ]]; then
    tunnel_id="$(cat "${_CF_STATE_TUNNEL_ID}")"
  fi

  echo ""
  echo "╔════════════════════════════════════════════════════════════════╗"
  echo "║         Cloudflare Tunnel Bootstrap Complete                   ║"
  echo "╚════════════════════════════════════════════════════════════════╝"
  echo ""
  echo "  All VPS inbound ports are CLOSED."
  echo "  Traffic flows: Internet → Cloudflare Edge → Tunnel → Cluster"
  echo ""
  if [[ -n "$tunnel_id" ]]; then
    echo "  Tunnel ID: ${tunnel_id}"
  fi
  echo ""
  echo "  ── Platform Access ──────────────────────────────────────────"
  echo "  ArgoCD:   https://argocd.${domain}"
  echo "  Keycloak: https://auth.${domain}"
  echo "  Grafana:  https://grafana.${domain}"
  echo ""
  echo "  ── SSH Access via Cloudflare Zero Trust ─────────────────────"
  echo "  1. Install cloudflared locally: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
  echo "  2. Configure SSH in ~/.ssh/config:"
  echo ""
  echo "       Host *.${domain}"
  echo "         ProxyCommand cloudflared access ssh --hostname %h"
  echo ""
  echo "  3. Create a Zero Trust SSH application:"
  echo "     https://one.dash.cloudflare.com → Access → Applications → Add"
  echo "     Type: Self-hosted | Domain: node1.${domain}"
  echo ""
  echo "  4. SSH to a node:"
  echo "     ssh root@node1.${domain}"
  echo ""
  echo "  ── Zero Trust Dashboard ─────────────────────────────────────"
  echo "  https://one.dash.cloudflare.com"
  echo ""
  echo "  ── Verify Bootstrap ─────────────────────────────────────────"
  echo "  ./bootstrap/verify.sh"
  echo ""
}
