{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "code-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ include "code-server.host" . }}
      secretName: {{ include "code-server.fullname" . }}-tls
  {{- end }}
  rules:
    - host: {{ include "code-server.host" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "code-server.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
