apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "code-server.fullname" . }}-workspace
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.workspace.storageClass }}
  accessModes:
    {{- toYaml .Values.workspace.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
