apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "code-server.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "code-server.selectorLabels" . | nindent 6 }}
