apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "k6-operator.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k6-operator.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "k6-operator.selectorLabels" . | nindent 6 }}
