apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-datasource-loki
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki-wrapper.labels" . | nindent 4 }}
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://{{ .Release.Name }}-loki-gateway.{{ .Release.Namespace }}.svc.cluster.local
        version: 1
        editable: false
        jsonData:
          maxLines: 1000
