apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequireResourceLimits
metadata:
  name: require-resource-limits
  labels:
    {{- include "opa-gatekeeper.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  enforcementAction: {{ .Values.constraintEnforcementAction }}
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
