#!/usr/bin/env bash
# cluster/kind/bootstrap.sh
#
# KIND-001a: Provisions a 3-node local kind cluster (sovereign-test) and
# emits cluster-values.yaml conforming to contract/v1/cluster.schema.yaml.
#
# Platform components (Cilium, cert-manager, sealed-secrets, MinIO) are
# installed by platform/deploy.sh in KIND-001b — not this script.
#
# Usage:
#   ./cluster/kind/bootstrap.sh [--domain DOMAIN] [--output PATH] [--dry-run]
#
# Prerequisites:
#   brew install kind kubectl

set -euo pipefail

DOMAIN="sovereign.local"
OUTPUT="cluster-values.yaml"
DRY_RUN=false
CLUSTER_NAME="sovereign-test"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

usage() {
  echo "Usage: $0 [--cluster-name NAME] [--domain DOMAIN] [--output PATH] [--dry-run]"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cluster-name) CLUSTER_NAME="$2"; shift 2 ;;
    --domain)       DOMAIN="$2";       shift 2 ;;
    --output)       OUTPUT="$2";       shift 2 ;;
    --dry-run)      DRY_RUN=true;      shift   ;;
    --help)         usage ;;
    *) echo "Unknown flag: $1"; usage ;;
  esac
done

log() { echo "==> $*"; }

if [[ "$DRY_RUN" == "true" ]]; then
  log "DRY RUN — no cluster will be created"
  log "Would create: kind cluster '${CLUSTER_NAME}' (3 nodes: 1 control-plane + 2 workers)"
  log "Would write: ${OUTPUT} (cluster-values.yaml conforming to contract/v1)"
  log "Would validate: python3 contract/validate.py ${OUTPUT}"
  exit 0
fi

# ── 1. Create kind cluster ────────────────────────────────────────────────────
log "Bootstrapping kind cluster: ${CLUSTER_NAME}"
if kind get clusters 2>/dev/null | grep -q "^${CLUSTER_NAME}$"; then
  log "Cluster '${CLUSTER_NAME}' already exists — skipping creation"
else
  log "Creating kind cluster '${CLUSTER_NAME}' (3 nodes)..."
  kind create cluster \
    --name "${CLUSTER_NAME}" \
    --config "${SCRIPT_DIR}/kind-config.yaml" \
    --wait 90s
fi

KUBE_CONTEXT="kind-${CLUSTER_NAME}"
log "Cluster ready. Context: ${KUBE_CONTEXT}"

# ── 2. Write cluster-values.yaml ─────────────────────────────────────────────
log "Writing ${OUTPUT}..."
cat > "${OUTPUT}" <<EOF
apiVersion: sovereign.dev/cluster/v1
kind: ClusterValues

# Generated by cluster/kind/bootstrap.sh
# Conforms to contract/v1/cluster.schema.yaml
# Validate with: python3 contract/validate.py ${OUTPUT}

runtime:
  domain: ${DOMAIN}
  imageRegistry:
    internal: ""  # empty during bootstrap; set to harbor.${DOMAIN}/sovereign after Harbor deploy

storage:
  block:
    storageClassName: standard
  file:
    storageClassName: standard  # kind: RWO only (local-path); acceptable for local testing
  object:
    endpoint: http://minio.minio.svc:9000  # installed by platform/deploy.sh (KIND-001b)
    credentialsSecret: minio-credentials

network:
  ingressClass: nginx
  networkPolicyEnforced: true  # enforced by Cilium (installed by platform/deploy.sh)

pki:
  clusterIssuer: selfsigned-cluster-issuer  # created by cert-manager (installed by platform/deploy.sh)

autarky:
  externalEgressBlocked: true
  imagesFromInternalRegistryOnly: true
EOF

# ── 3. Validate output against contract ──────────────────────────────────────
log "Validating ${OUTPUT} against contract..."
python3 "${SCRIPT_DIR}/../../contract/validate.py" "${OUTPUT}"

log ""
log "Kind cluster ready: ${CLUSTER_NAME}"
log "Smoke test:  helm install test-release cluster/kind/charts/sealed-secrets/ \\"
log "               --namespace sealed-secrets --create-namespace \\"
log "               --kube-context kind-${CLUSTER_NAME} --wait"
log "Tear down:   kind delete cluster --name ${CLUSTER_NAME}"
