#!/usr/bin/env bash
# cluster/kind/bootstrap.sh
#
# Provisions a local kind cluster that satisfies the sovereign cluster contract.
# Outputs: cluster-values.yaml conforming to contract/v1/cluster.schema.yaml
#
# Usage:
#   ./cluster/kind/bootstrap.sh [--domain sovereign.local] [--output cluster-values.yaml]
#   ./cluster/kind/bootstrap.sh --dry-run
#
# Prerequisites:
#   brew install kind kubectl helm

set -euo pipefail

DOMAIN="sovereign.local"
OUTPUT="cluster-values.yaml"
DRY_RUN=false
CLUSTER_NAME="sovereign-test"

usage() {
  echo "Usage: $0 [--cluster-name NAME (default: sovereign-test)] [--domain DOMAIN] [--output PATH] [--dry-run]"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cluster-name) CLUSTER_NAME="$2"; shift 2 ;;
    --domain)       DOMAIN="$2";       shift 2 ;;
    --output)       OUTPUT="$2";       shift 2 ;;
    --dry-run)      DRY_RUN=true;      shift   ;;
    --help)         usage ;;
    *) echo "Unknown flag: $1"; usage ;;
  esac
done

log() { echo "==> $*"; }

if [[ "$DRY_RUN" == "true" ]]; then
  log "DRY RUN — no cluster will be created"
  log "Would create: kind cluster '${CLUSTER_NAME}' (3 nodes, Cilium CNI)"
  log "Would install: cert-manager, sealed-secrets, local-path-provisioner, MinIO"
  log "Would write: ${OUTPUT}"
  exit 0
fi

log "Bootstrapping kind cluster: ${CLUSTER_NAME}"

# ── 1. Create kind cluster ────────────────────────────────────────────────
log "Creating kind cluster '${CLUSTER_NAME}'..."
if kind get clusters 2>/dev/null | grep -q "^${CLUSTER_NAME}$"; then
  log "Cluster '${CLUSTER_NAME}' already exists — skipping creation"
else
  kind create cluster \
    --name "${CLUSTER_NAME}" \
    --config "$(dirname "$0")/kind-config.yaml" \
    --wait 60s
fi

KUBE_CONTEXT="kind-${CLUSTER_NAME}"
log "Cluster ready. Context: ${KUBE_CONTEXT}"

# ── 2. Install Cilium (replaces kindnet — enforces NetworkPolicy) ────────
log "Installing Cilium CNI..."
helm upgrade --install cilium "$(dirname "$0")/charts/cilium/" \
  --kube-context "${KUBE_CONTEXT}" \
  --namespace kube-system \
  --wait --timeout 3m

# ── 3. Install cert-manager ───────────────────────────────────────────────
log "Installing cert-manager..."
helm upgrade --install cert-manager "$(dirname "$0")/charts/cert-manager/" \
  --kube-context "${KUBE_CONTEXT}" \
  --namespace cert-manager --create-namespace \
  --wait --timeout 3m

# Create a self-signed ClusterIssuer
kubectl --context "${KUBE_CONTEXT}" apply -f - <<EOF
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}
EOF

# ── 4. Install Sealed Secrets ─────────────────────────────────────────────
log "Installing Sealed Secrets..."
helm upgrade --install sealed-secrets "$(dirname "$0")/charts/sealed-secrets/" \
  --kube-context "${KUBE_CONTEXT}" \
  --namespace sealed-secrets --create-namespace \
  --wait --timeout 2m

# ── 5. Install local-path-provisioner (block + file storage for kind) ────
log "Installing local-path-provisioner..."
kubectl --context "${KUBE_CONTEXT}" apply -f \
  https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.26/deploy/local-path-storage.yaml

# NOTE: this is the one external URL call — only during cluster bootstrap,
# never during platform operation. Replace with vendored copy in a future story.

kubectl --context "${KUBE_CONTEXT}" patch storageclass local-path \
  -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

# ── 6. Install MinIO (S3-compatible object storage for kind) ─────────────
log "Installing MinIO..."
helm upgrade --install minio oci://registry-1.docker.io/bitnamicharts/minio \
  --kube-context "${KUBE_CONTEXT}" \
  --namespace minio --create-namespace \
  --set auth.rootUser=sovereign \
  --set auth.rootPassword=sovereign \
  --set persistence.storageClass=local-path \
  --wait --timeout 3m

# NOTE: MinIO image also fetched externally during bootstrap — same note as above.

# Create S3 credentials secret in default namespace for platform use
kubectl --context "${KUBE_CONTEXT}" create secret generic minio-credentials \
  --from-literal=access-key=sovereign \
  --from-literal=secret-key=sovereign \
  --dry-run=client -o yaml | kubectl --context "${KUBE_CONTEXT}" apply -f -

# ── 7. Write cluster-values.yaml ─────────────────────────────────────────
log "Writing ${OUTPUT}..."
cat > "${OUTPUT}" <<EOF
apiVersion: sovereign.dev/cluster/v1
kind: ClusterValues

# Generated by cluster/kind/bootstrap.sh
# Conforms to contract/v1/cluster.schema.yaml
# Validate with: python3 contract/validate.py ${OUTPUT}

runtime:
  domain: ${DOMAIN}
  imageRegistry:
    internal: ""  # empty during bootstrap — set to harbor.${DOMAIN}/sovereign after platform deploy

storage:
  block:
    storageClassName: local-path
  file:
    storageClassName: local-path    # kind: RWO only; acceptable for local testing
  object:
    endpoint: http://minio.minio.svc:9000
    credentialsSecret: minio-credentials

network:
  ingressClass: nginx
  networkPolicyEnforced: true

pki:
  clusterIssuer: selfsigned-cluster-issuer

autarky:
  externalEgressBlocked: true
  imagesFromInternalRegistryOnly: true
EOF

# ── 8. Validate output against contract ──────────────────────────────────
log "Validating ${OUTPUT} against contract..."
python3 "$(dirname "$0")/../../contract/validate.py" "${OUTPUT}"

log ""
log "Kind cluster ready. Next step:"
log "  cd platform && ./deploy.sh --cluster-values ../${OUTPUT}"
