#!/usr/bin/env bash
# cluster/kind/ha-bootstrap.sh
#
# HA-004: Provisions a 5-node kind cluster (sovereign-ha) with 3 control-plane
# nodes and 2 worker nodes, then validates autarky invariants via
# contract/validate.py.
#
# Usage:
#   ./cluster/kind/ha-bootstrap.sh [--cluster-name NAME] [--domain DOMAIN] [--output PATH] [--dry-run]

set -euo pipefail

CLUSTER_NAME="sovereign-ha"
DOMAIN="sovereign.local"
OUTPUT="cluster-values.yaml"
DRY_RUN=false
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

usage() {
  echo "Usage: $0 [--cluster-name NAME] [--domain DOMAIN] [--output PATH] [--dry-run]"
  exit 1
}

log() { echo "==> $*"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cluster-name) CLUSTER_NAME="$2"; shift 2 ;;
    --domain)       DOMAIN="$2";       shift 2 ;;
    --output)       OUTPUT="$2";       shift 2 ;;
    --dry-run)      DRY_RUN=true;      shift   ;;
    --help)         usage ;;
    *) echo "Unknown flag: $1"; usage ;;
  esac
done

if [[ "$DRY_RUN" == "true" ]]; then
  log "DRY RUN — no cluster will be created"
  log "Would create: kind cluster '${CLUSTER_NAME}' (5 nodes: 3 control-plane + 2 workers)"
  log "Would use config: ${SCRIPT_DIR}/kind-ha-config.yaml"
  log "Would write: ${OUTPUT} (cluster-values.yaml conforming to contract/v1)"
  log "Would validate: python3 contract/validate.py ${OUTPUT}"
  exit 0
fi

# ── 1. Create kind cluster ────────────────────────────────────────────────────
log "Bootstrapping HA kind cluster: ${CLUSTER_NAME}"
if kind get clusters 2>/dev/null | grep -q "^${CLUSTER_NAME}$"; then
  log "Cluster '${CLUSTER_NAME}' already exists — skipping creation"
else
  log "Creating HA kind cluster '${CLUSTER_NAME}' (3 control-plane + 2 workers)..."
  kind create cluster \
    --name "${CLUSTER_NAME}" \
    --config "${SCRIPT_DIR}/kind-ha-config.yaml" \
    --wait 120s
fi

KUBE_CONTEXT="kind-${CLUSTER_NAME}"
log "Cluster ready. Context: ${KUBE_CONTEXT}"

# Verify node count
NODE_COUNT=$(kubectl get nodes --context "${KUBE_CONTEXT}" --no-headers 2>/dev/null | wc -l | tr -d ' ')
log "Node count: ${NODE_COUNT} (expected 5)"

CP_COUNT=$(kubectl get nodes --context "${KUBE_CONTEXT}" --no-headers \
  -l node-role.kubernetes.io/control-plane 2>/dev/null | wc -l | tr -d ' ')
log "Control-plane nodes: ${CP_COUNT} (expected 3)"

# ── 2. Write cluster-values.yaml ─────────────────────────────────────────────
log "Writing ${OUTPUT}..."
cat > "${OUTPUT}" <<EOF
apiVersion: sovereign.dev/cluster/v1
kind: ClusterValues

# Generated by cluster/kind/ha-bootstrap.sh
# Conforms to contract/v1/cluster.schema.yaml
# Validate with: python3 contract/validate.py ${OUTPUT}

runtime:
  domain: ${DOMAIN}
  imageRegistry:
    internal: ""  # empty during bootstrap; set to harbor.${DOMAIN}/sovereign after Harbor deploy

storage:
  block:
    storageClassName: standard
  file:
    storageClassName: standard
  object:
    endpoint: http://minio.minio.svc:9000
    credentialsSecret: minio-credentials

network:
  ingressClass: nginx
  networkPolicyEnforced: true

pki:
  clusterIssuer: selfsigned-cluster-issuer

autarky:
  externalEgressBlocked: true
  imagesFromInternalRegistryOnly: true
EOF

# ── 3. Validate output against contract ──────────────────────────────────────
log "Validating ${OUTPUT} against contract..."
python3 "${SCRIPT_DIR}/../../contract/validate.py" "${OUTPUT}"

log ""
log "HA kind cluster ready: ${CLUSTER_NAME}"
log "PASS"
