replicaCount: 2

global:
  domain: "sovereign-autarky.dev"
  storageClass: "ceph-block"
  imageRegistry: ""  # set to harbor.<domain>/sovereign after Harbor is running
  keycloak:
    url: "https://auth.sovereign-autarky.dev"
    realm: "sovereign"

controllerManager:
  image:
    repository: "chaos-mesh/chaos-mesh"
    name: "chaos-mesh/chaos-mesh"
    tag: "v2.6.3-abc1234-p0"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

podDisruptionBudget:
  minAvailable: 1
