{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vscode-extension-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vscode-extension-registry.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - vsix.{{ .Values.global.domain }}
      secretName: vscode-extension-registry-tls
  rules:
    - host: vsix.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vscode-extension-registry.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
