apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vscode-extension-registry.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vscode-extension-registry.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "vscode-extension-registry.selectorLabels" . | nindent 6 }}
