apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vscode-extension-registry.fullname" . }}-vsix
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vscode-extension-registry.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.vsix.storageClass }}
  accessModes:
    {{- toYaml .Values.vsix.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.vsix.storageSize }}
