apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sovereign-pm.fullname" . }}-prd
  namespace: sovereign-pm
  labels:
    app.kubernetes.io/name: sovereign-pm
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.prdPvc.accessMode }}
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.prdPvc.storageRequest }}
