{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-sonarqube
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sonarqube-wrapper.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ include "sonarqube-wrapper.host" . }}
      secretName: {{ .Release.Name }}-sonarqube-tls
  {{- end }}
  rules:
    - host: {{ include "sonarqube-wrapper.host" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-sonarqube
                port:
                  number: 9000
{{- end }}
