apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "selenium-grid.fullname" . }}-hub-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "selenium-grid.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "selenium-grid.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: hub
