apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "forgejo-sovereign.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgejo-sovereign.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: "sovereign-ca-issuer"
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ include "forgejo-sovereign.host" . | quote }}
      secretName: forgejo-tls
  rules:
    - host: {{ include "forgejo-sovereign.host" . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-forgejo-http
                port:
                  number: 3000
