apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zot.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "zot.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "zot.selectorLabels" . | nindent 20 }}
                topologyKey: kubernetes.io/hostname
      containers:
        - name: zot
          image: {{ include "zot.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - serve
            - /etc/zot/config.json
          ports:
            - name: registry
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: config
              mountPath: /etc/zot
              readOnly: true
            - name: data
              mountPath: /var/lib/registry
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: {{ include "zot.fullname" . }}-config
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "zot.fullname" . }}-data
        - name: tmp
          emptyDir: {}
