apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: sovereign-platform
    app.kubernetes.io/component: observability
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  revisionHistoryLimit: 3
  source:
    repoURL: https://github.com/libliflin/sovereign
    targetRevision: HEAD
    path: charts/thanos
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.domain
          value: sovereign-autarky.dev
  destination:
    server: https://kubernetes.default.svc
    namespace: thanos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
