apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailpit.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mailpit.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mailpit.selectorLabels" . | nindent 4 }}
  ports:
    - name: smtp
      port: {{ .Values.service.smtpPort }}
      targetPort: smtp
      protocol: TCP
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
