{{- /*
  PodDisruptionBudgets for cert-manager components.
*/ -}}
{{- $components := list "cert-manager" "cainjector" "webhook" -}}
{{- range $components }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ . }}-pdb
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cert-manager.labels" $ | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ . }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
