apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  annotations:
    # Deploy Crossplane early (after CNI), before any compositions are applied
    argocd.argoproj.io/sync-wave: "-90"
    argocd-image-updater.argoproj.io/image-list: "app=harbor.sovereign-autarky.dev/sovereign/crossplane"
    argocd-image-updater.argoproj.io/app.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  labels:
    app.kubernetes.io/part-of: sovereign-platform
    tier: platform
spec:
  revisionHistoryLimit: 3
  project: default
  source:
    repoURL: https://github.com/libliflin/sovereign
    targetRevision: HEAD
    path: charts/crossplane
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
