apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-60"
  labels:
    app.kubernetes.io/name: istio
    app.kubernetes.io/part-of: sovereign-security
spec:
  revisionHistoryLimit: 3
  project: default
  source:
    repoURL: https://github.com/libliflin/sovereign
    targetRevision: HEAD
    path: charts/istio
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.domain
          value: sovereign-autarky.dev
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
