{{- /*
  PodDisruptionBudgets for Vault components.
*/ -}}
{{- $components := list "vault" "vault-agent-injector" -}}
{{- range $components }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ . }}-pdb
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault.labels" $ | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ . }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
