apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage.fullname" . }}-app-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
data:
  app-config.production.yaml: |
    app:
      baseUrl: "https://{{ include "backstage.host" . }}"
    backend:
      baseUrl: "https://{{ include "backstage.host" . }}"
    auth:
      environment: production
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true
    {{- with .Values.backstage.appConfig }}
    catalog:
      providers:
        gitea:
          forgejo:
            host: {{ .catalog.providers.forgejo.host | quote }}
            catalogPath: {{ .catalog.providers.forgejo.catalogPath | quote }}
            branch: {{ .catalog.providers.forgejo.branch | quote }}
            entityFilename: {{ .catalog.providers.forgejo.entityFilename | quote }}
    kubernetes:
      serviceLocatorMethod:
        type: {{ .kubernetes.serviceLocatorMethod.type | quote }}
      clusterLocatorMethods:
        {{- range .kubernetes.clusterLocatorMethods }}
        - type: {{ .type | quote }}
          clusters:
            {{- range .clusters }}
            - url: {{ .url | quote }}
              name: {{ .name | quote }}
              authProvider: {{ .authProvider | quote }}
              skipTLSVerify: {{ .skipTLSVerify }}
              skipMetricsLookup: {{ .skipMetricsLookup }}
            {{- end }}
        {{- end }}
    argocd:
      username: {{ .argocd.username | quote }}
      appLocatorMethods:
        {{- range .argocd.appLocatorMethods }}
        - type: {{ .type | quote }}
          instances:
            {{- range .instances }}
            - name: {{ .name | quote }}
              url: {{ .url | quote }}
            {{- end }}
        {{- end }}
    techdocs:
      builder: {{ .techdocs.builder | quote }}
      generator:
        runIn: {{ .techdocs.generator.runIn | quote }}
      publisher:
        type: {{ .techdocs.publisher.type | quote }}
        awsS3:
          bucketName: {{ .techdocs.publisher.awsS3.bucketName | quote }}
          region: {{ .techdocs.publisher.awsS3.region | quote }}
          endpoint: {{ .techdocs.publisher.awsS3.endpoint | quote }}
          s3ForcePathStyle: {{ .techdocs.publisher.awsS3.s3ForcePathStyle }}
    {{- end }}
