{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "backstage.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "backstage.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  serviceName: {{ include "backstage.fullname" . }}-postgresql
  template:
    metadata:
      labels:
        {{- include "backstage.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
    spec:
      containers:
        - name: postgresql
          image: "{{ if .Values.postgresql.image.registry }}{{ .Values.postgresql.image.registry }}/{{ end }}{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: POSTGRESQL_USERNAME
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - pg_isready -U {{ .Values.postgresql.auth.username | quote }} -d {{ .Values.postgresql.auth.database | quote }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - pg_isready -U {{ .Values.postgresql.auth.username | quote }} -d {{ .Values.postgresql.auth.database | quote }}
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.global.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.postgresql.storage.size | quote }}
{{- end }}
