apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientSecret: {{ .Values.keycloak.clientSecret | quote }}
